#!/bin/bash
#PBS -l select=1:ncpus=24
#PBS -q smp
#PBS -l walltime=13:40:00
#PBS -P CSCI1142
#PBS -o /mnt/lustre/users/smkhatshwa/Masters/AUTOFAC//vncsession.out
#PBS -e /mnt/lustre/users/smkhatshwa/Masters/AUTOFAC//vncsession.err
### PBS -J 1-10:1
#PBS -m abe
#PBS -M mkhsin035@myuct.ac.za
#PBS -N EER-SSCI
ulimit -s unlimited
###  This following line will write the hostname of your compute node to the file hostname.txt
hostname > hostname.txt


cd /home/smkhatshwa/lustre/Masters/AUTOFAC/robogen/build && ./robogen-file-viewer ../CollectiveGatheringTask/front_active_wheel_robot_model_sensor_morph.txt ../CollectiveGatheringTask/environment-2/con6.txt --seed 6 --no-visualization
